// Generated by CoffeeScript 1.10.0
(function() {
  var routes;

  routes = {
    '/': 'IndexController@index',
    '/hotel/(.+)': 'HotelController@hotel_details',
    '/member': 'MemberController@index',
    '/member/register': 'MemberController@register',
    '/member/register.do/(.+)': 'MemberController@register',
    '/member/login.do/(.+)': 'MemberController@login',
    '/member/logout': 'MemberController@logout',
    '/flight': 'FlightController@index'
  };

  module.exports = {
    run: function() {
      return $(window).on('hashchange', function() {
        var args, controller, e, error, i, len, method, path, ref, ref1, regex, route;
        $('#loader').fadeIn(250);

        /* reset content */
        path = location.hash.startsWith('#!/') ? location.hash.slice(2) : '/';
        ref = Object.keys(routes);
        for (i = 0, len = ref.length; i < len; i++) {
          route = ref[i];
          regex = new RegExp('^' + route + '$');
          if (!regex.test(path)) {
            continue;
          }
          args = regex.exec(path);

          /* remove first item (path) from args */
          args.shift();
          ref1 = routes[route].split('@'), controller = ref1[0], method = ref1[1];

          /* require the controller and pass the params */
          controller = require('controller/' + controller);
          try {
            controller[method].apply(window, args);
            $('#loader').fadeOut(250);
            return;
          } catch (error) {
            e = error;
            console.log(e);

            /* ignore to show 404 */
          }
        }

        /* show 404 for unknown path */
        render('404').into('#content');
        return $('#loader').fadeOut(250);
      });
    }
  };

}).call(this);
