// Generated by CoffeeScript 1.10.0
(function() {
  var FlightController,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  module.exports = new (FlightController = (function() {
    function FlightController() {
      this.index = bind(this.index, this);
    }

    FlightController.prototype.index = function(id) {
      var Flight, flights;
      Flight = require('model/Flight');
      flights = Flight.all();
      return render('flight/index')["with"]({
        flights: flights,
        Airport: require('model/Airport')
      }).into('#content');
    };

    return FlightController;

  })());

}).call(this);
