// Generated by CoffeeScript 1.10.0
(function() {
  var HotelController;

  module.exports = new (HotelController = (function() {
    function HotelController() {}

    HotelController.prototype.hotel_details = function(id) {
      var Hotel, hotel, renderer;
      Hotel = require('model/Hotel');
      Hotel.update(id, {
        name: 'Century Hotel @ ' + (+(new Date) / 1000 | 0),
        rating: 3
      });
      hotel = Hotel.find(id);
      if (hotel !== null) {
        renderer = render('hotel/details').data({
          'hotel_id': id,
          'hotel_name': hotel.name,
          'hotel_rating': '★'.repeat(hotel.rating)
        });
      } else {
        renderer = render('404');
      }
      return renderer.into('#content');
    };

    return HotelController;

  })());

}).call(this);
