// Generated by CoffeeScript 1.10.0
(function() {
  var IndexController;

  module.exports = new (IndexController = (function() {
    function IndexController() {}

    IndexController.prototype.index = function() {
      return render('index').into('#content');
    };

    return IndexController;

  })());

}).call(this);
