// Generated by CoffeeScript 1.10.0
(function() {
  var HotelController;

  module.exports = new (HotelController = (function() {
    function HotelController() {}

    HotelController.prototype.index = function() {
      if (null !== localStorage.getItem('User')) {
        return render('member/index').into('#content');
      } else {
        return render('member/login').into('#content');
      }
    };

    HotelController.prototype.login = function(data) {
      var Member, form, mem;
      form = JSON.parse(atob(data));
      Member = require('model/Member');
      mem = Member.findByUsername(form.username);
      if (null === mem || mem.password !== form.password) {
        alert('Incorrect username or password');
        return location.hash = '#!/member';
      } else {
        localStorage.setItem('User', mem.username);
        return location.hash = '#!/';
      }
    };

    HotelController.prototype.logout = function() {
      localStorage.removeItem('User');
      return location.hash = '#!/';
    };

    HotelController.prototype.register = function(data) {
      var attr, form;
      if (!data) {
        return render('member/register').into('#content');
      } else {
        form = JSON.parse(atob(data));
        for (attr in form) {
          console.log(attr + ': ' + form[attr]);
        }
        alert('Registration success');
        return location.hash = '#!/member';
      }
    };

    return HotelController;

  })());

}).call(this);
