// Generated by CoffeeScript 1.10.0
(function() {
  var Airport;

  module.exports = new (Airport = (function() {
    function Airport() {}

    Airport.prototype.store = {
      'MEL': {
        name: 'Melbourne Airport',
        country: 'au'
      },
      'CBR': {
        name: 'Canberra International Airport',
        country: 'au'
      },
      'AKL': {
        name: 'Auckland Airport',
        country: 'nz'
      },
      'SIN': {
        name: 'Singapore Changi Airport',
        country: 'sg'
      },
      'HKG': {
        name: 'Hong Kong International Airport',
        country: 'hk'
      },
      'HND': {
        name: 'Tokyo International Airport',
        country: 'jp'
      },
      'KIX': {
        name: 'Kansai International Airport',
        country: 'jp'
      },
      'ICN': {
        name: 'Incheon International Airport',
        country: 'kr'
      },
      'JFK': {
        name: 'John F. Kennedy International Airport',
        country: 'us'
      },
      'LCY': {
        name: 'London City Airport',
        country: 'gb'
      },
      'PEK': {
        name: 'Beijing Capital International Airport',
        country: 'cn'
      },
      'SZX': {
        name: 'Shenzhen Baoan International Airport',
        country: 'cn'
      }
    };

    Airport.prototype.find = function(id) {
      if (this.store.hasOwnProperty(id)) {
        return this.store[id];
      } else {
        return null;
      }
    };

    return Airport;

  })());

}).call(this);
