// Generated by CoffeeScript 1.10.0
(function() {
  var Hotel;

  module.exports = new (Hotel = (function() {
    function Hotel() {}

    Hotel.prototype.store = {
      '13456': {
        name: 'Shangri-la oriental hotel',
        rating: 5
      }
    };

    Hotel.prototype.find = function(id) {
      if (this.store.hasOwnProperty(id)) {
        return this.store[id];
      } else {
        return null;
      }
    };

    Hotel.prototype.update = function(id, attrs) {
      var attr, results;
      if (attrs == null) {
        attrs = {};
      }
      if (this.store.hasOwnProperty(id)) {
        results = [];
        for (attr in attrs) {
          results.push(this.store[id][attr] = attrs[attr]);
        }
        return results;
      }
    };

    return Hotel;

  })());

}).call(this);
